10.1	Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1.	Initialize an empty array with size 2X2.
2.	Initialize an all one array with size 4X2.
3.	Return a new array of given shape and type, filled with fill  value.{Hint: np.full}
4.	Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5.	Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6.	For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np
empty_array = np.empty((2, 2))
print(empty_array)

[[1.85917342e-316 0.00000000e+000]
 [1.58101007e-322 3.10794597e+048]]


In [ ]:
ones_array = np.ones((4, 2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
filled_array = np.full((3, 3), 7)  # 3x3 matrix filled with 7
print(filled_array)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
example_array = np.array([[2, 3], [4, 5]])
zeros_like_array = np.zeros_like(example_array)
print(zeros_like_array)

[[0 0]
 [0 0]]


In [ ]:
ones_like_array = np.ones_like(example_array)
print(ones_like_array)

[[1 1]
 [1 1]]


In [ ]:
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print(numpy_array)

[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1.	Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2.	Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3.	Create a 3X3 identity matrix.{Hint:np.eye()}
4.	Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5.	Create a 10X10 array with random values and find the minimum and maximum values.
6.	Create a zero array of size 10 and replace 5th element with 1.
7.	Reverse an array arr = [1,2,0,0,4,0].
8.	Create a 2d array with 1 on border and 0 inside.
9.	Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np
array_range = np.arange(10, 50)
print(array_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random Array:", random_array)
print("Mean:", mean_value)

Random Array: [0.92228374 0.30037464 0.72884108 0.89685087 0.21113221 0.31778902
 0.9154547  0.38401121 0.21034557 0.79943441 0.79009418 0.05582507
 0.86861843 0.34948537 0.70749632 0.75548525 0.446786   0.72252335
 0.15569502 0.61511634 0.44625683 0.40615865 0.49210728 0.32482864
 0.48014771 0.59644633 0.64232936 0.91124811 0.16887979 0.09718664]
Mean: 0.5239744043498044


In [ ]:
random_matrix = np.random.random((10, 10))
min_value = random_matrix.min()
max_value = random_matrix.max()
print("Minimum:", min_value)
print("Maximum:", max_value)

Minimum: 0.0066737455704436455
Maximum: 0.9948319474321237


In [ ]:
zero_array = np.zeros(10)
zero_array[4] = 1  # 5th element (index 4) set to 1
print(zero_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)

[0 4 0 0 2 1]


In [ ]:
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print(border_array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]); Complete all the task using numpy:
1.	Add the two array.
2.	Subtract the two array.
3.	Multiply the array with any integers of your choice.
4.	Find the square of each element of the array.
5.	Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6.	Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.
7.	Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [ ]:
sum_xy = x + y
print(sum_xy)

[[ 6  8]
 [10 13]]


In [ ]:
diff_xy = x - y
print(diff_xy)

[[-4 -4]
 [-4 -3]]


In [ ]:
mult_x = x * 3
print(mult_x)

[[ 3  6]
 [ 9 15]]


In [ ]:
square_x = x ** 2
print(square_x)

[[ 1  4]
 [ 9 25]]


In [ ]:
# Dot product of v and w
dot_vw = np.dot(v, w)
print("Dot Product of v and w:", dot_vw)

# Dot product of x and v
dot_xv = np.dot(x, v)
print("Dot Product of x and v:", dot_xv)

# Dot product of x and y
dot_xy = np.dot(x, y)
print("Dot Product of x and y:\n", dot_xy)

Dot Product of v and w: 219
Dot Product of x and v: [29 77]
Dot Product of x and y:
 [[19 22]
 [50 58]]


In [ ]:
concat_xy = np.concatenate((x, y), axis=0)
print("Concatenated x and y along rows:\n", concat_xy)

concat_vw = np.vstack((v, w))
print("Concatenated v and w along columns:\n", concat_vw)

Concatenated x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenated v and w along columns:
 [[ 9 10]
 [11 12]]


In [ ]:
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print(concat_xv)
except ValueError as e:
    print("Error:", e)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [ ]:
v_reshaped = v.reshape(1, -1)  # Convert v to 2D row vector
concat_xv_fixed = np.concatenate((x, v_reshaped), axis=0)
print(concat_xv_fixed)

[[ 1  2]
 [ 3  5]
 [ 9 10]]


Problem - 4: Matrix Operations: • For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]); Prove following with Numpy:
1.	Prove A.A−1 = I.
2.	Prove AB ̸= BA.
3.	Prove (AB)T = BTAT.
•	Solve the following system of Linear equation using Inverse Methods.
2x − 3y + z = −1 x − y + 2z = −3 3x + y − z = 9
{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
•	Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}

In [ ]:
import numpy as np

In [ ]:
# Given matrix
A = np.array([[3, 4], [7, 8]])

# Compute inverse of A
A_inv = np.linalg.inv(A)

# Compute A * A_inv
result = np.dot(A, A_inv)

# Round the result to avoid floating-point errors
result = np.round(result, decimals=5)

print("A * A⁻¹ =\n", result)

A * A⁻¹ =
 [[1. 0.]
 [0. 1.]]


In [ ]:
# Given matrices
B = np.array([[5, 3], [2, 1]])

# Compute AB and BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB =\n", AB)
print("BA =\n", BA)

# Check if AB == BA
are_equal = np.array_equal(AB, BA)
print("Is AB equal to BA?", are_equal)

AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
Is AB equal to BA? False


In [ ]:
# Compute (AB)^T
AB_T = np.transpose(AB)

# Compute B^T and A^T separately
B_T = np.transpose(B)
A_T = np.transpose(A)

# Compute B^T * A^T
BT_AT = np.dot(B_T, A_T)

# Compare (AB)^T with B^T A^T
is_equal = np.array_equal(AB_T, BT_AT)

print("(AB)^T =\n", AB_T)
print("B^T A^T =\n", BT_AT)
print("Is (AB)^T equal to B^T A^T?", is_equal)

(AB)^T =
 [[23 51]
 [13 29]]
B^T A^T =
 [[23 51]
 [13 29]]
Is (AB)^T equal to B^T A^T? True


In [ ]:
# Coefficient matrix A
A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])

# Constants matrix B
B = np.array([-1, -3, 9])


In [ ]:
# Compute inverse of A
A_inv = np.linalg.inv(A)

# Solve for X
X = np.dot(A_inv, B)

print("Solution for [x, y, z]:", X)

Solution for [x, y, z]: [ 2.  1. -2.]


In [ ]:
X_solve = np.linalg.solve(A, B)
print("Solution using np.linalg.solve:", X_solve)

Solution using np.linalg.solve: [ 2.  1. -2.]


10.2	Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:
•	Using Python Lists, perform element-wise addition of two lists of size 1,000,000. Measure and Print the time taken for this operation.
•	Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
2. Element-wise Multiplication
•	Using Python Lists, perform element-wise multiplication of two lists of size 1,000,000. Measure and Print the time taken for this operation.
•	Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
3. Dot Product
•	Using Python Lists, compute the dot product of two lists of size 1,000,000. Measure and Print the time taken for this operation.
•	Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
4. Matrix Multiplication
•	Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
•	Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

In [ ]:
import numpy as np
import time

In [ ]:
size = 1_000_000  # 1 million elements
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()

print("Time taken for element-wise addition using Python lists:", end_time - start_time, "seconds")

Time taken for element-wise addition using Python lists: 0.16833043098449707 seconds


In [ ]:
array1 = np.arange(size)
array2 = np.arange(size)

start_time = time.time()
result_array = array1 + array2
end_time = time.time()

print("Time taken for element-wise addition using NumPy:", end_time - start_time, "seconds")

Time taken for element-wise addition using NumPy: 0.006703615188598633 seconds


In [ ]:
start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()

print("Time taken for element-wise multiplication using Python lists:", end_time - start_time, "seconds")

Time taken for element-wise multiplication using Python lists: 0.1654045581817627 seconds


In [ ]:
start_time = time.time()
result_array = array1 * array2
end_time = time.time()

print("Time taken for element-wise multiplication using NumPy:", end_time - start_time, "seconds")

Time taken for element-wise multiplication using NumPy: 0.002660989761352539 seconds


In [ ]:
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()

print("Time taken for dot product using Python lists:", end_time - start_time, "seconds")

Time taken for dot product using Python lists: 0.058106184005737305 seconds


In [ ]:
start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()

print("Time taken for dot product using NumPy:", end_time - start_time, "seconds")

Time taken for dot product using NumPy: 0.0010268688201904297 seconds


In [ ]:
size_matrix = 1000  # 1000x1000 matrix
matrix1 = [[i for i in range(size_matrix)] for _ in range(size_matrix)]
matrix2 = [[i for i in range(size_matrix)] for _ in range(size_matrix)]

start_time = time.time()
result_matrix = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(size_matrix)) for j in range(size_matrix)] for i in range(size_matrix)]
end_time = time.time()

print("Time taken for matrix multiplication using Python lists:", end_time - start_time, "seconds")

Time taken for matrix multiplication using Python lists: 129.82972240447998 seconds


In [ ]:
matrix1_np = np.arange(size_matrix**2).reshape(size_matrix, size_matrix)
matrix2_np = np.arange(size_matrix**2).reshape(size_matrix, size_matrix)

start_time = time.time()
result_matrix_np = np.dot(matrix1_np, matrix2_np)
end_time = time.time()

print("Time taken for matrix multiplication using NumPy:", end_time - start_time, "seconds")

Time taken for matrix multiplication using NumPy: 0.9411542415618896 seconds
